---

- name: set pin facts
  set_fact:
    _pin_package: elasticsearch
    _pin_version: "{{ elasticsearch_release }}"

- name: set elasticsearch preferences file
  template:
    src: pin.pref.j2
    dest: "/etc/apt/preferences.d/elasticsearch.pref"
    owner: root
    group: root
    mode: 0644

- name: install elasticsearch packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - elasticsearch

- name: update min heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: "-Xms{{ elasticsearch_heap_size }}"

- name: update max heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: "-Xmx{{ elasticsearch_heap_size }}"

- name: set ulimit nofile
  lineinfile:
    path: /etc/security/limits.conf
    line: 'elasticsearch  -  nofile  65536'

- name: set ulimit nproc
  lineinfile:
    path: /etc/security/limits.conf
    line: 'elasticsearch  -  nproc  4096'

- name: bind to ip
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host'
    line: "network.host: {{ elasticsearch_network_host }}"
  when: elasticsearch_network_host is defined

- name: deactivate xpack
  blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    marker: "# {mark} deactivate xpack"
    content: |
      xpack.security.enabled: false
      xpack.monitoring.enabled: false
      xpack.watcher.enabled: false
      xpack.ml.enabled: false

#- name: update elasticsearch.yml
#  template:
#    src: elasticsearch.yml.j2
#    dest: "/etc/elasticsearch/elasticsearch.yml"
#    owner: root
#    group: root
#    mode: 0644
#  register: _elasticsearch_config

- name: start elasticsearch
  systemd:
    name: "elasticsearch"
    state: started
    enabled: yes

...
