---

- name: set pin facts
  set_fact:
    _pin_package: kibana
    _pin_version: "{{ elasticsearch_release }}"

- name: set kibana preferences file
  template:
    src: pin.pref.j2
    dest: "/etc/apt/preferences.d/kibana.pref"
    owner: root
    group: root
    mode: 0644

- name: install kibana packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - kibana

- name: bind to ip
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^server.host:'
    line: "server.host: {{ elasticsearch_kibana_listen_ip }}"
    insertafter: "^#server.host:"
  when: elasticsearch_kibana_listen_ip is defined

- name: bind to port
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^server.port:'
    line: "server.port: {{ elasticsearch_kibana_listen_port }}"
    insertafter: "^#server.port:"
  when: elasticsearch_kibana_listen_port is defined

- name: set elasticsearch hosts
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^elasticsearch.hosts:'
    line: "elasticsearch.hosts: {{ elasticsearch_kibana_elasticsearch_hosts }}"
    insertafter: "^#elasticsearch.hosts:"
  when: elasticsearch_kibana_elasticsearch_hosts is defined

# - name: deactivate xpack
#   blockinfile:
#     path: /etc/kibana/kibana.yml
#     marker: "# {mark} deactivate xpack"
#     content: |
#       xpack.license_management.enabled: false
#       xpack.rollup.enabled: false
#       xpack.apm.enabled: false
#       xpack.grokdebugger.enabled: false
#       xpack.searchprofiler.enabled: false
#       xpack.graph.enabled: false
#       xpack.infra.enabled: false
#       xpack.ml.enabled: false
#       xpack.monitoring.enabled: false
#       xpack.reporting.enabled: false
#       xpack.security.enabled: false
#       xpack.security.audit.enabled: false
#       xpack.spaces.enabled: false

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: start kibana
  systemd:
    name: "kibana"
    state: started
    enabled: yes

- name: pause for one minute to allow kibana to come up
  pause:
    minutes: 1

...
